services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app  # sync current directory with app dir
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    volumes:  # Data volume in database
      - postgres_data:/var/lib/postgresql/data  # data are also accessible in container
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U postgres
      interval: 2s
      retries: 10
volumes:  # Data volume in container
  postgres_data: