"""empty message

Revision ID: 926dfcf491e9
Revises: dd1fd54097b9
Create Date: 2024-09-14 16:22:47.258555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926dfcf491e9'
down_revision = 'dd1fd54097b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
